PORT_SPEED=57600
BOARD=pro328
LIBRARYPATH=../libraries /Applications/Arduino.app/Contents/Resources/Java/libraries
include ../Arduino.mk

# Note:
# make upload
# make monitor
# to exit screen Ctrl+a, k
